In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
numbers = [1, 13, 4, 5, 63, 100]
numbers

[1, 13, 4, 5, 63, 100]

In [4]:
new_numbers = []

for n in numbers:
    new_numbers.append(n * 2)

print(new_numbers)

[2, 26, 8, 10, 126, 200]


In [5]:
new_numbers = [n * 2 for n in numbers]
print(new_numbers)

[2, 26, 8, 10, 126, 200]


In [6]:
for i in range(2):
    for j in range(5):
        print(i + j, end = " ")

0 1 2 3 4 1 2 3 4 5 

In [7]:
new_list_comprehension_1 = [i + j for i in range(2) for j in range(5)]
new_list_comprehension_1

[0, 1, 2, 3, 4, 1, 2, 3, 4, 5]

In [8]:
type(new_list_comprehension_1)

list

In [9]:
print(new_list_comprehension_1)

[0, 1, 2, 3, 4, 1, 2, 3, 4, 5]


In [10]:
new_list_comprehension_2 = [[i + j for i in range(2)] for j in range(5)]
new_list_comprehension_2

[[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]]

In [11]:
type(new_list_comprehension_2)

list

In [12]:
type(new_list_comprehension_1[1])

int

In [13]:
type(new_list_comprehension_2[1])

list

In [14]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
[num * 3 for num in range(1,11) if num % 2 != 0]

[3, 9, 15, 21, 27]

In [16]:
for i in range(1,11):
    if i % 2 != 0:
        print(i ** 3, end = ", ")

1, 27, 125, 343, 729, 

In [17]:
[num ** 3  if num % 2 != 0 else "even" for num in range(1,11)]

[1, 'even', 27, 'even', 125, 'even', 343, 'even', 729, 'even']

In [18]:
def raise_to_the_power_of_2(x):
    return x ** 2

In [19]:
raise_to_the_power_of_2(3)

9

In [20]:
lambda x: x ** 2

<function __main__.<lambda>(x)>

In [21]:
raise_to_the_power_of_2_lambda = lambda x: x ** 2

In [22]:
raise_to_the_power_of_2_lambda(3)

9

In [23]:
(lambda x: x/2) (11)

5.5

In [24]:
sum_xy = lambda x, y: x + y
sum_xy(2,3)

5

In [25]:
cal_xy = lambda x, y: x + y(x)

In [26]:
cal_xy(2, lambda x: x * 5)

12

In [27]:
base_url = "https://api.exchangeratesapi.io/v1/"

In [28]:
pip install requests

Note: you may need to restart the kernel to use updated packages.


In [29]:
import requests

In [30]:
x = requests.get('https://w3schools.com/python/demopage.htm')

print(x.text)

<!DOCTYPE html>
<html>
<body>

<h1>This is a Test Page</h1>

</body>
</html>


In [31]:
response = requests.get(base_url)

In [32]:
print(response)

<Response [401]>


In [33]:
response.ok

False

In [34]:
response.status_code

401

In [35]:
test_url = "https://api.coindesk.com/v1/bpi/currentprice.json"

In [36]:
test_response = requests.get(test_url)
print(test_response.text)

{"time":{"updated":"Jun 4, 2024 17:00:33 UTC","updatedISO":"2024-06-04T17:00:33+00:00","updateduk":"Jun 4, 2024 at 18:00 BST"},"disclaimer":"This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org","chartName":"Bitcoin","bpi":{"USD":{"code":"USD","symbol":"&#36;","rate":"70,712.314","description":"United States Dollar","rate_float":70712.3137},"GBP":{"code":"GBP","symbol":"&pound;","rate":"55,318.314","description":"British Pound Sterling","rate_float":55318.3137},"EUR":{"code":"EUR","symbol":"&euro;","rate":"65,005.759","description":"Euro","rate_float":65005.7593}}}


In [37]:
data = pd.DataFrame(test_response)

In [38]:
print(data)

                                                   0
0  b'{"time":{"updated":"Jun 4, 2024 17:00:33 UTC...
1  b'disclaimer":"This data was produced from the...
2  b'nversion rate from openexchangerates.org","c...
3  b'"description":"United States Dollar","rate_f...
4  b'ption":"British Pound Sterling","rate_float"...
5              b':"Euro","rate_float":65005.7593}}}'


In [39]:
url = "https://api.agify.io?name=Shreyasi"

In [40]:
url2 = "https://dog.ceo/api/breeds/image/random"

In [41]:
url_response = requests.get(url)
print(url_response.text)

{"count":11,"name":"Shreyasi","age":38}


In [42]:
new_data = pd.DataFrame(url_response)
print(new_data)

                                            0
0  b'{"count":11,"name":"Shreyasi","age":38}'


In [43]:
test_response.json()

{'time': {'updated': 'Jun 4, 2024 17:00:33 UTC',
  'updatedISO': '2024-06-04T17:00:33+00:00',
  'updateduk': 'Jun 4, 2024 at 18:00 BST'},
 'disclaimer': 'This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org',
 'chartName': 'Bitcoin',
 'bpi': {'USD': {'code': 'USD',
   'symbol': '&#36;',
   'rate': '70,712.314',
   'description': 'United States Dollar',
   'rate_float': 70712.3137},
  'GBP': {'code': 'GBP',
   'symbol': '&pound;',
   'rate': '55,318.314',
   'description': 'British Pound Sterling',
   'rate_float': 55318.3137},
  'EUR': {'code': 'EUR',
   'symbol': '&euro;',
   'rate': '65,005.759',
   'description': 'Euro',
   'rate_float': 65005.7593}}}

In [44]:
import json

In [45]:
json.dumps(test_response.json(), indent = 4)

'{\n    "time": {\n        "updated": "Jun 4, 2024 17:00:33 UTC",\n        "updatedISO": "2024-06-04T17:00:33+00:00",\n        "updateduk": "Jun 4, 2024 at 18:00 BST"\n    },\n    "disclaimer": "This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org",\n    "chartName": "Bitcoin",\n    "bpi": {\n        "USD": {\n            "code": "USD",\n            "symbol": "&#36;",\n            "rate": "70,712.314",\n            "description": "United States Dollar",\n            "rate_float": 70712.3137\n        },\n        "GBP": {\n            "code": "GBP",\n            "symbol": "&pound;",\n            "rate": "55,318.314",\n            "description": "British Pound Sterling",\n            "rate_float": 55318.3137\n        },\n        "EUR": {\n            "code": "EUR",\n            "symbol": "&euro;",\n            "rate": "65,005.759",\n            "description": "Euro",\n            "rate_f

In [46]:
print(json.dumps(test_response.json(), indent = 4))

{
    "time": {
        "updated": "Jun 4, 2024 17:00:33 UTC",
        "updatedISO": "2024-06-04T17:00:33+00:00",
        "updateduk": "Jun 4, 2024 at 18:00 BST"
    },
    "disclaimer": "This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org",
    "chartName": "Bitcoin",
    "bpi": {
        "USD": {
            "code": "USD",
            "symbol": "&#36;",
            "rate": "70,712.314",
            "description": "United States Dollar",
            "rate_float": 70712.3137
        },
        "GBP": {
            "code": "GBP",
            "symbol": "&pound;",
            "rate": "55,318.314",
            "description": "British Pound Sterling",
            "rate_float": 55318.3137
        },
        "EUR": {
            "code": "EUR",
            "symbol": "&euro;",
            "rate": "65,005.759",
            "description": "Euro",
            "rate_float": 65005.7593
        }
 

In [47]:
test_response.json().keys()

dict_keys(['time', 'disclaimer', 'chartName', 'bpi'])

In [48]:
import pandas as pd

In [49]:
import numpy as np

In [50]:
pip install upgrade numpy

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade


In [51]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B': 16600, 'Product C': 15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [52]:
prices_per_category.values

array([22250, 16600, 15600], dtype=int64)

In [53]:
type(prices_per_category.values)

numpy.ndarray

In [54]:
prices_per_category.array

<NumpyExtensionArray>
[22250, 16600, 15600]
Length: 3, dtype: int64

In [55]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.NumpyExtensionArray

In [56]:
prices_per_category.to_numpy()

array([22250, 16600, 15600], dtype=int64)

In [57]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [58]:
prices_per_category.values[0]

22250

In [59]:
type(prices_per_category.values[0])

numpy.int64

In [60]:
prices_per_category.array[0]

22250

In [61]:
type(prices_per_category.array[0])

numpy.int64

In [62]:
prices_per_category.to_numpy()[0]

22250

In [63]:
type(prices_per_category.to_numpy()[0])

numpy.int64

In [64]:
num = pd.Series([15, 1000, 23, 45, 444])
num

0      15
1    1000
2      23
3      45
4     444
dtype: int64

In [65]:
num.sort_values()

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [66]:
num.sort_values(ascending=True)

0      15
2      23
3      45
4     444
1    1000
dtype: int64

In [67]:
num.sort_values(ascending=False)

1    1000
4     444
3      45
2      23
0      15
dtype: int64

In [68]:
DATA = pd.read_csv('Location.csv')
location_data = DATA.copy().squeeze()
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [69]:
location_data.sort_values()

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [70]:
location_data.sort_values(ascending=True)

637     Location 1
884     Location 1
465     Location 1
716    Location 10
623    Location 10
          ...     
482    Location 97
128    Location 97
669    Location 97
757    Location 98
372    Location 99
Name: Location, Length: 1043, dtype: object

In [71]:
location_data.sort_values(ascending=False)

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [72]:
DATA = pd.read_csv('Location.csv')
location_data = DATA.copy().squeeze()
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [73]:
location_data.index

RangeIndex(start=0, stop=1043, step=1)

In [74]:
location_data.name

'Location'

In [75]:
location_data.index.name

In [76]:
location_data.index.name='Index'

In [77]:
location_data

Index
0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [78]:
location_data.index.name

'Index'

In [79]:
location_data.index.to_numpy()

array([   0,    1,    2, ..., 1040, 1041, 1042], dtype=int64)

In [80]:
DATA = pd.read_csv('Location.csv')
location_data = DATA.copy().squeeze()
location_data.head()

0     Location 3
1     Location 6
2     Location 8
3    Location 26
4    Location 34
Name: Location, dtype: object

In [81]:
location_data_sv = location_data.sort_values(ascending=False)
location_data_sv.head()

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [82]:
location_data_sv.index

Index([ 372,  757,  128,  482,  271,  669,  612,   29,  518,  598,
       ...
        904,  912, 1010,   14,  716,  202,  298,  637,  884,  465],
      dtype='int64', length=1043)

In [83]:
location_data_sv.index.sort_values()

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042],
      dtype='int64', length=1043)

In [84]:
location_data_sv.head()

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [85]:
location_data_sv.index = location_data_sv.index.sort_values()

In [86]:
location_data_sv

0       Location 99
1       Location 98
2       Location 97
3       Location 97
4       Location 97
           ...     
1038    Location 10
1039    Location 10
1040     Location 1
1041     Location 1
1042     Location 1
Name: Location, Length: 1043, dtype: object

In [87]:
location_data_sv = location_data.sort_values(ascending = False)
location_data_sv.head()

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
Name: Location, dtype: object

In [88]:
location_data_sv.sort_index()

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [89]:
location_data_sv

372    Location 99
757    Location 98
128    Location 97
482    Location 97
271    Location 97
          ...     
202    Location 10
298    Location 10
637     Location 1
884     Location 1
465     Location 1
Name: Location, Length: 1043, dtype: object

In [90]:
location_data_sv = location_data_sv.sort_index(ascending=True)
location_data_sv

0        Location 3
1        Location 6
2        Location 8
3       Location 26
4       Location 34
           ...     
1038    Location 73
1039    Location 82
1040    Location 11
1041    Location 26
1042    Location 94
Name: Location, Length: 1043, dtype: object

In [91]:
array_a = np.array([[3, 2, 1], [6, 3, 2]])
array_a

array([[3, 2, 1],
       [6, 3, 2]])

In [92]:
pd.DataFrame(array_a)

0  1  2
0  3  2  1
1  6  3  2

In [93]:
type(pd.DataFrame(array_a))

pandas.core.frame.DataFrame

In [94]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', 'Column 3'], index = ['Row 1', 'Row 2'])
df

Column 1  Column 2  Column 3
Row 1         3         2         1
Row 2         6         3         2

In [95]:
data = pd.read_csv('Lending-company.csv', index_col = 'LoanID')
lending_co_data = data.copy()
lending_co_data.head()

StringID    Product CustomerGender     Location    Region  TotalPrice  \
LoanID                                                                          
1       LoanID_1  Product B         Female   Location 3  Region 2     17600.0   
2       LoanID_2  Product D         Female   Location 6  Region 6         NaN   
3       LoanID_3  Product B           Male   Location 8  Region 3     16600.0   
4       LoanID_4  Product A           Male  Location 26  Region 2     17600.0   
5       LoanID_5  Product B         Female  Location 34  Region 3     21250.0   

         StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
LoanID                                                                      
1       04/07/2018     2200         45          365       3221       4166   
2       02/01/2019     2200         45          365       3161       4096   
3       08/12/2016     1000         45          365       2260       3205   
4              NaN     2200         45          365       3141       4166   
5       28/10/2017     2200         55          365       3570       4745   

        AmtPaid360 LoanStatus  
LoanID                         
1            14621     Active  
2            16041     Active  
3            16340        NaN  
4            16321     Active  
5            14720     Active

In [96]:
type(lending_co_data)

pandas.core.frame.DataFrame

In [97]:
lending_co_data.axes

[Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
        ...
        1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043],
       dtype='int64', name='LoanID', length=1043),
 Index(['StringID', 'Product', 'CustomerGender', 'Location', 'Region',
        'TotalPrice', 'StartDate', 'Deposit', 'DailyRate', 'TotalDaysYr',
        'AmtPaid36', 'AmtPaid60', 'AmtPaid360', 'LoanStatus'],
       dtype='object')]

In [98]:
lending_co_data.dtypes

StringID           object
Product            object
CustomerGender     object
Location           object
Region             object
TotalPrice        float64
StartDate          object
Deposit             int64
DailyRate           int64
TotalDaysYr         int64
AmtPaid36           int64
AmtPaid60           int64
AmtPaid360          int64
LoanStatus         object
dtype: object

In [99]:
A = lending_co_data.values
A

array([['LoanID_1', 'Product B', 'Female', ..., 4166, 14621, 'Active'],
       ['LoanID_2', 'Product D', 'Female', ..., 4096, 16041, 'Active'],
       ['LoanID_3', 'Product B', 'Male', ..., 3205, 16340, nan],
       ...,
       ['LoanID_1041', 'Product A', 'NotSpecified', ..., 5143, 16617,
        'Finished Payment'],
       ['LoanID_1042', 'Product B', 'Female', ..., 3462, 15617,
        'Finished Payment'],
       ['LoanID_1043', 'Product A', 'NotSpecified', ..., 4743, 16617,
        'Finished Payment']], dtype=object)

In [100]:
type(lending_co_data.values)

numpy.ndarray

In [101]:
B = lending_co_data.to_numpy()
B

array([['LoanID_1', 'Product B', 'Female', ..., 4166, 14621, 'Active'],
       ['LoanID_2', 'Product D', 'Female', ..., 4096, 16041, 'Active'],
       ['LoanID_3', 'Product B', 'Male', ..., 3205, 16340, nan],
       ...,
       ['LoanID_1041', 'Product A', 'NotSpecified', ..., 5143, 16617,
        'Finished Payment'],
       ['LoanID_1042', 'Product B', 'Female', ..., 3462, 15617,
        'Finished Payment'],
       ['LoanID_1043', 'Product A', 'NotSpecified', ..., 4743, 16617,
        'Finished Payment']], dtype=object)

In [102]:
type(lending_co_data.to_numpy())

numpy.ndarray

In [103]:
lending_co_data.shape

(1043, 14)

In [104]:
len(lending_co_data.columns)

14

In [105]:
data = pd.read_csv('Lending-company.csv', index_col = 'StringID')
lending_co_data = data.copy()
lending_co_data.head()

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_2       2  Product D         Female   Location 6  Region 6         NaN   
LoanID_3       3  Product B           Male   Location 8  Region 3     16600.0   
LoanID_4       4  Product A           Male  Location 26  Region 2     17600.0   
LoanID_5       5  Product B         Female  Location 34  Region 3     21250.0   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_2  02/01/2019     2200         45          365       3161       4096   
LoanID_3  08/12/2016     1000         45          365       2260       3205   
LoanID_4         NaN     2200         45          365       3141       4166   
LoanID_5  28/10/2017     2200         55          365       3570       4745   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_2       16041     Active  
LoanID_3       16340        NaN  
LoanID_4       16321     Active  
LoanID_5       14720     Active

In [106]:
lending_co_data.Product

StringID
LoanID_1       Product B
LoanID_2       Product D
LoanID_3       Product B
LoanID_4       Product A
LoanID_5       Product B
                 ...    
LoanID_1039    Product B
LoanID_1040    Product A
LoanID_1041    Product A
LoanID_1042    Product B
LoanID_1043    Product A
Name: Product, Length: 1043, dtype: object

In [107]:
lending_co_data.Location

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [108]:
lending_co_data['Product']

StringID
LoanID_1       Product B
LoanID_2       Product D
LoanID_3       Product B
LoanID_4       Product A
LoanID_5       Product B
                 ...    
LoanID_1039    Product B
LoanID_1040    Product A
LoanID_1041    Product A
LoanID_1042    Product B
LoanID_1043    Product A
Name: Product, Length: 1043, dtype: object

In [109]:
lending_co_data['Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [110]:
lending_co_data[['Location','Product']]

Location    Product
StringID                           
LoanID_1      Location 3  Product B
LoanID_2      Location 6  Product D
LoanID_3      Location 8  Product B
LoanID_4     Location 26  Product A
LoanID_5     Location 34  Product B
...                  ...        ...
LoanID_1039  Location 73  Product B
LoanID_1040  Location 82  Product A
LoanID_1041  Location 11  Product A
LoanID_1042  Location 26  Product B
LoanID_1043  Location 94  Product A

[1043 rows x 2 columns]

In [111]:
type(lending_co_data[['Location']])

pandas.core.frame.DataFrame

In [112]:
prod_loc = ['Location', 'Product']
lending_co_data[prod_loc].head()

Location    Product
StringID                        
LoanID_1   Location 3  Product B
LoanID_2   Location 6  Product D
LoanID_3   Location 8  Product B
LoanID_4  Location 26  Product A
LoanID_5  Location 34  Product B

In [113]:
lending_co_data.iloc[1]

LoanID                     2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: LoanID_2, dtype: object

In [114]:
lending_co_data.iloc[1, 3]

'Location 6'

In [115]:
lending_co_data.iloc[1, :]

LoanID                     2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: LoanID_2, dtype: object

In [116]:
lending_co_data.iloc[:, 3]

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [117]:
lending_co_data.iloc[[1, 3], :]

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_2       2  Product D         Female   Location 6  Region 6         NaN   
LoanID_4       4  Product A           Male  Location 26  Region 2     17600.0   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_2  02/01/2019     2200         45          365       3161       4096   
LoanID_4         NaN     2200         45          365       3141       4166   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_2       16041     Active  
LoanID_4       16321     Active

In [118]:
lending_co_data.iloc[:, [3, 1]]

Location    Product
StringID                           
LoanID_1      Location 3  Product B
LoanID_2      Location 6  Product D
LoanID_3      Location 8  Product B
LoanID_4     Location 26  Product A
LoanID_5     Location 34  Product B
...                  ...        ...
LoanID_1039  Location 73  Product B
LoanID_1040  Location 82  Product A
LoanID_1041  Location 11  Product A
LoanID_1042  Location 26  Product B
LoanID_1043  Location 94  Product A

[1043 rows x 2 columns]

In [119]:
lending_co_data.loc['LoanID_3']

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [120]:
lending_co_data.loc['LoanID_3', :]

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [121]:
lending_co_data.loc['LoanID_3', 'Region']

'Region 3'

In [122]:
lending_co_data['Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [123]:
lending_co_data.loc[:, 'Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...     
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [124]:
lending_co_data['TotalPrice'].loc['LoanID_1']

17600.0

In [125]:
lending_co_data['TotalPrice'][0]

C:\Users\arnab\AppData\Local\Temp\ipykernel_13624\1605309455.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lending_co_data['TotalPrice'][0]


17600.0

In [126]:
lending_co_data['TotalPrice']['LoanID_1']

17600.0

In [127]:
lending_co_data.iloc[0][5]

C:\Users\arnab\AppData\Local\Temp\ipykernel_13624\1538933843.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  lending_co_data.iloc[0][5]


17600.0

In [128]:
lending_co_data.iloc[0, 5]

17600.0

In [129]:
lending_co_data.iloc[[0, 5]]

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_6       6  Product A           Male  Location 34  Region 1         NaN   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_6  19/04/2019     2200         45          365       3301       4066   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_6       15141     Active

In [130]:
lending_co_data.iloc[[0, 5], :]

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_6       6  Product A           Male  Location 34  Region 1         NaN   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_6  19/04/2019     2200         45          365       3301       4066   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_6       15141     Active

In [131]:
lending_co_data['TotalPrice']['LoanID_1']

17600.0

In [132]:
lending_co_data.loc['LoanID_1', 'TotalPrice']

17600.0

In [133]:
lending_co_data.loc[['LoanID_1', 'LoanID_6']]

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_6       6  Product A           Male  Location 34  Region 1         NaN   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_6  19/04/2019     2200         45          365       3301       4066   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_6       15141     Active

In [134]:
lending_co_data.loc[['LoanID_1', 'LoanID_6'], :]

LoanID    Product CustomerGender     Location    Region  TotalPrice  \
StringID                                                                        
LoanID_1       1  Product B         Female   Location 3  Region 2     17600.0   
LoanID_6       6  Product A           Male  Location 34  Region 1         NaN   

           StartDate  Deposit  DailyRate  TotalDaysYr  AmtPaid36  AmtPaid60  \
StringID                                                                      
LoanID_1  04/07/2018     2200         45          365       3221       4166   
LoanID_6  19/04/2019     2200         45          365       3301       4066   

          AmtPaid360 LoanStatus  
StringID                         
LoanID_1       14621     Active  
LoanID_6       15141     Active

In [135]:
lending_co_data['TotalPrice'].iloc[[0, 5]]

StringID
LoanID_1    17600.0
LoanID_6        NaN
Name: TotalPrice, dtype: float64

In [136]:
lending_co_data.loc[:, 'TotalPrice'].iloc[[0, 5]]

StringID
LoanID_1    17600.0
LoanID_6        NaN
Name: TotalPrice, dtype: float64

In [137]:
array_a = np.array([[1, 2, 3],[4, 5, 6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [138]:
array_a[0, 2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [139]:
list_a = [8, 7, 8]
array_a[0] = list_a
array_a

array([[8, 7, 8],
       [4, 5, 6]])

In [140]:
list_L = [1, 2, 3]
list_L

[1, 2, 3]

In [141]:
list_L + [2]

[1, 2, 3, 2]

In [142]:
array_a + 2

array([[10,  9, 10],
       [ 6,  7,  8]])

In [143]:
array_a = np.array([[1, 2, 3],[4, 5, 6]], dtype= "complex64")
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [144]:
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [145]:
array_a[:]

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [146]:
array_a[0:0]

array([], shape=(0, 3), dtype=complex64)

In [147]:
array_a[0:1]

array([[1.+0.j, 2.+0.j, 3.+0.j]], dtype=complex64)

In [148]:
array_a[1:2,0:1]

array([[4.+0.j]], dtype=complex64)

In [149]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4],[4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [159]:
matrix_B[::-1,::2]>2

array([[ True,  True, False],
       [ True,  True,  True],
       [False, False, False]])

In [162]:
matrix_B[(matrix_B[::,::]>2) & (matrix_B[::,::] %2 == 0)]

array([6, 6, 4, 4, 8])

In [163]:
matrix_B[(matrix_B[::,::]>2) | (matrix_B[::,::] %2 == 0)]

array([2, 0, 3, 6, 6, 7, 4, 4, 5, 3, 8, 0])

In [164]:
matrix_B[0,0]

1

In [168]:
type(matrix_B[0,0])

numpy.int32

In [169]:
type(matrix_B[0,0:1])

numpy.ndarray

In [170]:
type(matrix_B[0:1,0:1])

numpy.ndarray

In [172]:
print(matrix_B[0,0].shape)

()


In [173]:
print(matrix_B[0,0:1].shape)

(1,)


In [174]:
print(matrix_B[0:1,0:1].shape)

(1, 1)


In [175]:
matrix_B[0:1,0:1].squeeze()

array(1)

In [176]:
print(matrix_B[0:1,0:1].squeeze())

1


In [177]:
type(matrix_B[0:1,0:1].squeeze())

numpy.ndarray

In [178]:
matrix_B[0:1,0:1].squeeze().shape

()

In [180]:
np.squeeze(matrix_B[0:1,0:1])

array(1)