In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
np.__version__

'1.26.4'

In [4]:
pd.__version__

'2.2.2'

In [5]:
list_1 = [1, 2]
list_1

[1, 2]

In [6]:
list_2 = [34, 45]
list_2

[34, 45]

In [7]:
list_1.extend(list_2)

In [8]:
list_1

[1, 2, 34, 45]

importing numpy

In [9]:
import numpy as np

assigning a vector

In [10]:
v = np.array([5,-2,4])

In [11]:
v

array([ 5, -2,  4])

Assigning a matrix

In [12]:
m = np.array([[5,12,6],[-3,0,14]])

In [13]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

Data Types

In [14]:
type(v)

numpy.ndarray

In [15]:
type(m)

numpy.ndarray

In [16]:
s_array = np.array(5)

type(s_array)

numpy.ndarray

Data shapes

In [17]:
m.shape

(2, 3)

In [18]:
v.shape

(3,)

In [19]:
s_array.shape #it gives blank, that means it has no shape. because it is a scaler. and scaler has no shape.

()

Creating or reshaping a vector to a column vector

In [20]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [21]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

Creating a tensor

In [22]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [23]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [24]:
t = np.array([m1,m2])

t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [25]:
t.shape  # it means it consists two matrices 2 by 3 each.

(2, 2, 3)

Manually creating a tensor

In [26]:
t_manual = np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])

t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [27]:
t_manual.shape

(2, 2, 3)

Addition

In [28]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

Substraction

In [29]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

Addition and Substraction of vectors

In [30]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [31]:
v1 + v2

array([6, 6, 6, 6, 6])

In [32]:
v1 - v2

array([-4, -2,  0,  2,  4])

Addition & substraction of matrix with scaler

In [33]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [34]:
m2 - 2

array([[ 7,  6,  5],
       [-1,  1, -7]])

Transposing a matrix

In [35]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [36]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [37]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [38]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [39]:
C = np.array([[4,-5],[8,12],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [19,  0]])

In [40]:
C.T

array([[ 4,  8, 19],
       [-5, 12,  0]])

Transposing scalars

In [41]:
s = np.array([5])
s

array([5])

In [42]:
s.T

array([5])

Transposing vectors

In [43]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [44]:
x.T

array([1, 2, 3])

In [45]:
x.shape

(3,)

In [46]:
x_reshape = x.reshape(1,3)
x_reshape

array([[1, 2, 3]])

In [47]:
x_reshape.T

array([[1],
       [2],
       [3]])

Dot product

In [48]:
x =np.array([2,8,-4])
y = np.array([1,-7,3])

In [49]:
np.dot(x,y)

-66

In [50]:
u = np.array([0,2,5,8])
v = np.array([20,3,4,-1])

In [51]:
np.dot(u,v)

18

Scalar*Scalar

In [52]:
np.dot(10,-2)

-20

In [53]:
np.dot(5,6)

30

Scalar*Vector

In [54]:
x

array([ 2,  8, -4])

In [55]:
5*x

array([ 10,  40, -20])

Scalar*Matrix

In [56]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [57]:
3*A

array([[15, 36, 18],
       [-9,  0, 42]])

In [58]:
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [59]:
E = np.array([[2,-1],[8,0],[3,0]])
E

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [60]:
np.dot(A,E)

array([[124,  -5],
       [ 36,   3]])

In [61]:
np.__version__

'1.26.4'

In [62]:
import pandas as pd

In [63]:
products = ['A','B','C','D']
products

['A', 'B', 'C', 'D']

In [64]:
type(products)

list

In [65]:
product_categories = pd.Series(products)

In [66]:
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [67]:
type(product_categories)

pandas.core.series.Series

In [68]:
type(pd.Series(products))

pandas.core.series.Series

In [69]:
daily_rates_dollers = pd.Series([40, 45, 50, 60])
daily_rates_dollers

0    40
1    45
2    50
3    60
dtype: int64

In [70]:
print(daily_rates_dollers)

0    40
1    45
2    50
3    60
dtype: int64


In [71]:
array_a = np.array([10, 20, 30, 40, 50])
array_a

array([10, 20, 30, 40, 50])

In [72]:
type(array_a)

numpy.ndarray

In [73]:
series_a = pd.Series(array_a)
series_a

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [74]:
type(series_a)

pandas.core.series.Series

In [75]:
series_a.dtype

dtype('int32')

In [76]:
series_a.size

5

In [77]:
product_categories = pd.Series(['A','B','C','D'])
product_categories

0    A
1    B
2    C
3    D
dtype: object

In [78]:
product_categories.dtype

dtype('O')

In [79]:
product_categories.size

4

In [80]:
product_categories.name = "Product Categories"
product_categories.name

'Product Categories'

In [81]:
prices_per_category = {'Product A': 22250, 'Product B': 16600, 'Product C': 15600}
prices_per_category

{'Product A': 22250, 'Product B': 16600, 'Product C': 15600}

In [82]:
type(prices_per_category)

dict

In [83]:
prices_per_category = pd.Series(prices_per_category)
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [84]:
type(prices_per_category)

pandas.core.series.Series

In [85]:
prices_per_category.index

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [86]:
type(prices_per_category.index)

pandas.core.indexes.base.Index

In [87]:
prices_per_category = pd.Series({'Product A': 22250, 'Product B': 16600, 'Product C': 15600})
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [88]:
prices_per_category.index

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [89]:
type(prices_per_category.index)

pandas.core.indexes.base.Index

In [90]:
prices_per_category['Product A']

22250

In [91]:
prices_per_category[0]

C:\Users\arnab\AppData\Local\Temp\ipykernel_6896\1694906638.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prices_per_category[0]


22250

In [92]:
series_b = pd.Series([10,20,30,40,50], index = [1,2,3,4,5])
series_b

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [93]:
series_b[1]

10

In [94]:
series_c = pd.Series([10,20,30,40,50], index = ["1","2","3","4","5"])
series_c

1    10
2    20
3    30
4    40
5    50
dtype: int64

In [95]:
series_c[1]

C:\Users\arnab\AppData\Local\Temp\ipykernel_6896\2194739140.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  series_c[1]


20

In [96]:
series_c["1"]

10

In [97]:
prices_per_category

Product A    22250
Product B    16600
Product C    15600
dtype: int64

In [98]:
start_date_deposits = pd.Series({
    '7/4/2014'  :   2000,
    '1/2/2015'  :   2000,
    '12/8/2012' :   1000,
    '2/20/2015' :   2000,
    '10/28/2013':   2000,
    '4/19/2015' :   2000,
    '7/4/2016'  :   2000,
    '4/24/2014' :   2000,
    '9/3/2015'  :   4000,
    '7/25/2016' :   2000,
    '5/1/2014'  :   2000,
    '3/29/2013' :   2000,
    '10/3/2014' :   2000,
    '9/18/2015' :   2500
})

In [99]:
start_date_deposits

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
4/19/2015     2000
7/4/2016      2000
4/24/2014     2000
9/3/2015      4000
7/25/2016     2000
5/1/2014      2000
3/29/2013     2000
10/3/2014     2000
9/18/2015     2500
dtype: int64

In [100]:
start_date_deposits.sum()

29500

In [101]:
start_date_deposits.min()

1000

In [102]:
start_date_deposits.max()

4000

In [103]:
start_date_deposits.idxmax()

'9/3/2015'

In [104]:
start_date_deposits.idxmin()

'12/8/2012'

In [105]:
start_date_deposits.head()

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
dtype: int64

In [106]:
start_date_deposits.tail()

7/25/2016    2000
5/1/2014     2000
3/29/2013    2000
10/3/2014    2000
9/18/2015    2500
dtype: int64

In [107]:
start_date_deposits.head(3)

7/4/2014     2000
1/2/2015     2000
12/8/2012    1000
dtype: int64

In [108]:
start_date_deposits.head(10)

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
4/19/2015     2000
7/4/2016      2000
4/24/2014     2000
9/3/2015      4000
7/25/2016     2000
dtype: int64

In [109]:
start_date_deposits.head(n=10)

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
4/19/2015     2000
7/4/2016      2000
4/24/2014     2000
9/3/2015      4000
7/25/2016     2000
dtype: int64

In [110]:
start_date_deposits.sum()

29500

In [111]:
data = {'ProductName':['Product A','Product B','Product C'], 'ProductPrice':[22250,16600,12500]}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

In [112]:
import pandas as pd

data = [{'Name':'Amy White', 'Age':50, 'Working Experience (Yrs.)':5},
       {'Name':'Jack Stewart', 'Age':53, 'Working Experience (Yrs.)':8},
       {'Name':'Richard Lauderdale', 'Age':35, 'Working Experience (Yrs.)':3},
       {'Name':'Sara Johnson', 'Age':43, 'Working Experience (Yrs.)':10}]

df = pd.DataFrame(data)

print(df)

                 Name  Age  Working Experience (Yrs.)
0           Amy White   50                          5
1        Jack Stewart   53                          8
2  Richard Lauderdale   35                          3
3        Sara Johnson   43                         10


In [114]:
ser_products = pd.Series(['Product A','Product B', 'Product C'])
ser_products

0    Product A
1    Product B
2    Product C
dtype: object

In [115]:
ser_prices = pd.Series([22250,16600,12500])

ser_prices

0    22250
1    16600
2    12500
dtype: int64

In [117]:
data = {'ProductName':ser_products, 'ProductPrice':ser_prices}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

In [118]:
ser_products = pd.Series(['Product A','Product B', 'Product C'], index=['A','B','C'])
ser_prices = pd.Series([22250,16600,12500], index=['A','B','C'])
data = {'ProductName':ser_products, 'ProductPrice':ser_prices}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [120]:
data = [['Product A', 22250], ['Product B', 16600], ['Product C', 12500]]
df = pd.DataFrame(data)
df

0      1
0  Product A  22250
1  Product B  16600
2  Product C  12500

In [121]:
df.columns = ['ProductName', 'ProductPrice']
df

ProductName  ProductPrice
0   Product A         22250
1   Product B         16600
2   Product C         12500

In [122]:
df.index = ['A','B','C']
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [123]:
df = pd.DataFrame(data=[['Product A', 22250],['Product B', 16600],['Product C', 12500]], columns = ['ProductName', 'ProductPrice'], index = ['A','B','C'])
df

ProductName  ProductPrice
A   Product A         22250
B   Product B         16600
C   Product C         12500

In [124]:
df.shape

(3, 2)